# Generated by Django 6.0.7 on 2026-08-18 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('team_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('available_credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('escrow_credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('UNSOLD', 'Unsold')], default='QUEUED', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_highest_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_technologies', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='BidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_history', to='api.technology')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuctionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technology')),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('available_credits__gte', 0)), name='available_credits_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('escrow_credits__gte', 0)), name='escrow_credits_non_negative'),
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['status', 'end_time'], name='api_technol_status_6e3228_idx'),
        ),
        migrations.AddConstraint(
            model_name='technology',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='base_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='technology',
            constraint=models.CheckConstraint(condition=models.Q(('current_highest_bid__gte', 0)), name='bid_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='auctionparticipant',
            unique_together={('team', 'technology')},
        ),
    ]
