# Generated by Django 5.2.6 on 2026-05-16 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('available_credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('escrow_credits', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('available_credits__gte', 0)), name='available_credits_non_negative'), models.CheckConstraint(condition=models.Q(('escrow_credits__gte', 0)), name='escrow_credits_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('UNSOLD', 'Unsold')], default='QUEUED', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_highest_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='api.team')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'end_time'], name='api_technol_status_6e3228_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='base_price_non_negative'), models.CheckConstraint(condition=models.Q(('current_highest_bid__gte', 0)), name='bid_non_negative')],
            },
        ),
    ]
