# Generated by Django 5.2.6 on 2026-08-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('Core Technologies', 'Core Technologies'), ('Business Resources', 'Business Resources'), ('Premium Assets', 'Premium Assets')], default='Core Technologies', max_length=50),
        ),
        migrations.AddField(
            model_name='technology',
            name='max_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='technology',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='technology',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_won_technologies', to='api.team'),
        ),
        migrations.CreateModel(
            name='AssetPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_assets', to='api.team')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.technology')),
            ],
        ),
    ]
