# Generated by Django 6.0.7 on 2026-07-27 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auctionparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_technologies', to='api.team'),
        ),
        migrations.CreateModel(
            name='BidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_history', to='api.technology')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
