# Generated by Django 6.0.7 on 2026-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_technology_highest_bidder_bidlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(db_index=True, default='temp', max_length=10, unique=True),
        ),
    ]
