# Generated by Django 5.2.6 on 2026-08-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_technology_category_technology_max_stock_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='technology',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('status',), name='unique_active_auction'),
        ),
    ]
