# Generated by Django 6.0.7 on 2026-08-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_team_team_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
